version: "3"

services:
  execute-api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/user/src/app
  mysql_server:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=execute_db
      - MYSQL_ROOT_PASSWORD=
