version: "3.8"

services:
  execute-api:
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    links:
      - mysql_server
    depends_on:
      - mysql_server
    restart: on-failure
    command: bash -c "npm run migrate && npm run dev"
  mysql_server:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=execute_db
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}